name: prexp
description: Convert the path string to a regular expression, such as `/users/:name` and the like.
version: 0.1.0
repository: https://github.com/odroe/prexp

environment:
  sdk: '>=2.18.6 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
